# Generated by Django 5.2.7 on 2025-10-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonalish',
            name='aktiv',
            field=models.BooleanField(default=False),
        ),
    ]
