# Generated by Django 5.2.7 on 2025-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_yonalish_aktiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustoz',
            name='gender',
        ),
        migrations.AddField(
            model_name='ustoz',
            name='jins',
            field=models.CharField(default='Erkak', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ustoz',
            name='daraja',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ustoz',
            name='ism',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ustoz',
            name='yosh',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
